# Generated by Django 3.2.5 on 2021-07-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_commentmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
