# Generated by Django 3.2.5 on 2021-07-12 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0033_alter_commentmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment_likes',
            field=models.ManyToManyField(related_name='comment_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
