# Generated by Django 3.2.5 on 2021-07-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_commentmodel_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
