# Generated by Django 3.2.5 on 2021-07-28 04:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20210726_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='heading3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post3',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
